### ISSUE TITLE
Practica de logica proporcional y tablas de verdad

### ISSUE THREAD

**Issue by irving1613** [SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-erick-ramos#1]
[practica  -1.pdf](https://github.com/SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-erick-ramos/files/7549062/practica.-1.pdf)

**Comment by 71santiago7** [comment]
[PRACTICA 1.pdf](https://github.com/SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-erick-ramos/files/7549161/PRACTICA.1.pdf)

**Comment by saul19bautista** [comment]
calificación 26% 
falto describir más, la conclusión  debió ser de 12 renglones y no confundir introducción con objetivos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
